_format_version: "2.1"
_transform: true

services:
- name: hot-dog-service
  protocol: http
  host: hello-kubernetes-hot-dog.minikube.local
  port: 80
  path: /
  # url: http://ingress-nginx-controller.ingress-nginx/

routes:
- name: hot-dog-route
  service: hot-dog-service
  methods: []
  strip_path: true
  preserve_host: false
  paths:
  - /
