# Provide a custom message
message: "Ameba!"

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  enabled: true
  rewritePath: false
  pathPrefix: "/"
  annotations:
    kubernetes.io/ingress.class: nginx

service:
  type: ClusterIP
  port: 80
