{{- if .Values.grafana.sidecar.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "monitoring.fullname" . }}-loki-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "monitoring.name" . }}
    chart: {{ template "monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
      version: 1
{{- end }}
{{- end }}
