apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: grafana-data
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
