apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: loki-data
  name: loki-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
