apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes
type: monitoring
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: "kube-prometheus-stack"
  condition: kube-prometheus-stack.enabled
  version: "~16.0.1"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.3.0"
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.2.0"
