# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true

loki:
  enabled: true

promtail:
  enabled: true
